prometheusOperator:
  createCustomResource: true
  namespaces:
    releaseNamespace: true
    additional:
      - kube-system
      - default
      - monitoring
prometheus:
  enabled: true
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: true
    serviceMonitorSelector:
      matchLabels:
        release: prometheus